#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="/usr/bin/eww"

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    ${EWW_BIN} open calendar_win
    touch "$LOCK_FILE"
    run && echo "ok good!"

else
    ${EWW_BIN} close calendar_win
    rm "$LOCK_FILE" && echo "closed"
fi
